definitions:
  dto.AuthRequest:
    properties:
      email:
        type: string
      password:
        type: string
      userType:
        type: string
    required:
    - email
    - password
    - userType
    type: object
  dto.AuthResponse:
    properties:
      token:
        type: string
    type: object
  dto.OAuth2ClientResponse:
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
    type: object
  dto.UserRequest:
    properties:
      email:
        type: string
      fileId:
        type: string
      fullName:
        type: string
      id:
        type: string
      password:
        type: string
      userType:
        type: string
    required:
    - email
    - userType
    type: object
  model.BaseUser:
    properties:
      createdAt:
        type: string
      createdBy:
        type: string
      deletedBy:
        type: string
      email:
        type: string
      fullName:
        type: string
      id:
        type: string
      isDeleting:
        type: boolean
      password:
        type: string
      profilePath:
        type: string
      role:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      updatedAt:
        type: string
      updatedBy:
        type: string
      userType:
        type: string
    type: object
  model.Role:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Driver details
        in: body
        name: driver
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthResponse'
      summary: login to the site using this api
      tags:
      - Auth
  /auth/register-client/oauth:
    post:
      consumes:
      - application/json
      parameters:
      - description: auth details
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OAuth2ClientResponse'
      summary: register OAuth Client for your site
      tags:
      - Auth
  /temporary-attachments:
    post:
      consumes:
      - multipart/form-data
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: Get list of attachment id
      tags:
      - Temporary Attachments
  /tenant:
    post:
      consumes:
      - multipart/form-data
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: Create Tenant
      tags:
      - Temporary Attachments
  /user:
    post:
      consumes:
      - application/json
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BaseUser'
      summary: update user using this api
      tags:
      - user
  /user/doc/:id:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - user
swagger: "2.0"
